# Generated by Django 4.2.1 on 2023-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product_category',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='product_tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='cover_image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
    ]
