# Generated by Django 4.2.1 on 2023-05-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0001_initial'),
        ('product', '0002_remove_products_stock_alter_product_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name': 'product_ category', 'verbose_name_plural': 'product_categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product ', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brand.brand'),
        ),
    ]
