# Generated by Django 4.2.1 on 2023-06-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_products_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['price'], 'verbose_name': 'product ', 'verbose_name_plural': 'products'},
        ),
    ]
