# Generated by Django 4.2.1 on 2023-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_details',
            options={'verbose_name': 'Order_Detail', 'verbose_name_plural': 'Order_Details'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Inprogress', 'Inprogress'), ('Dispatch', 'Dispatch'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
