# Generated by Django 4.2.1 on 2023-06-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment_Detail', 'verbose_name_plural': 'Payment_Details'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Inprogress', 'Inprogress'), ('Dispatch', 'Dispatch'), ('Delivered', 'Delivered'), ('success', 'success'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
